🔨 [GH-0] updated github actions to align default workflow

diff --git a/.github/workflows/gradle_plugin_release.yml b/.github/workflows/gradle_plugin_release.yml
--- a/.github/workflows/gradle_plugin_release.yml
+++ b/.github/workflows/gradle_plugin_release.yml
@@ -16,6 +16,13 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v3
 
+      - name: Verify that branch matches pattern release/*
+        run: |
+          if [[ "${{ github.ref }}" != refs/heads/release/* ]]; then
+            echo "Error: This workflow must be triggered from a branch matching 'release/*'."
+            exit 1
+          fi
+
       - name: Verify user triggering the workflow
         id: verify-user
         run: |
diff --git a/.github/workflows/library_release.yml b/.github/workflows/library_release.yml
--- a/.github/workflows/library_release.yml
+++ b/.github/workflows/library_release.yml
@@ -6,7 +6,6 @@ on:
       branch:
         description: "Branch to release the library from"
         required: true
-        default: "main"
 
 jobs:
   validation:
@@ -15,6 +14,13 @@ jobs:
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
+
+      - name: Verify that branch matches pattern release/*
+        run: |
+          if [[ "${{ github.ref }}" != refs/heads/release/* ]]; then
+            echo "Error: This workflow must be triggered from a branch matching 'release/*'."
+            exit 1
+          fi
 
       - name: Verify user triggering the workflow
         id: verify-user
